export const getAllOrder = 'mbjzmxcx/getAllOrder'
export const getAllOrderItemByOnumber = 'mbjzmxcx/getAllOrderItemByOnumber'
// export const addOneNewOrder = 'diancan/addOneNewOrder'
// export const getAllOrderItemByOnumber = 'diancan/getAllOrderItemByOnumber'
// export const getOneOrderByOnumber = 'diancan/getOneOrderByOnumber'
// export const deleteOneOrderItemByOInumber = 'diancan/deleteOneOrderItemByOInumber'
// export const addOneBill = 'kt/addOneBill'
