export const getAllOrder = 'mbjzmxcx/getAllOrder'
export const getAllOrderItemByOnumber = 'mbjzmxcx/getAllOrderItemByOnumber'
export const deleteAllMessageByOTnumber = 'mbjzmxcx/deleteAllMessageByOTnumber'
export const updateTableState = 'mbjzmxcx/updateTableState'
// export const getOneOrderByOnumber = 'diancan/getOneOrderByOnumber'
// export const deleteOneOrderItemByOInumber = 'diancan/deleteOneOrderItemByOInumber'
// export const addOneBill = 'kt/addOneBill'
