export const getAllMenuByMSname = 'diancan/getAllMenuByMSname'
export const addOneOrderItem = 'diancan/addOneOrderItem'
export const addOneNewOrder = 'diancan/addOneNewOrder'
export const getAllOrderItemByOnumber = 'diancan/getAllOrderItemByOnumber'
export const getOneOrderByOnumber = 'diancan/getOneOrderByOnumber'
export const deleteOneOrderItemByOInumber = 'diancan/deleteOneOrderItemByOInumber'
export const addOneBill = 'diancan/addOneBill'
export const addOneNewMarket = 'diancan/addOneNewMarket'
