export const getAllTable = 'kt/getAllTable'
export const updateOneTable = 'kt/updateOneTable'
export const deleteOneReserve = 'kt/deleteOneReserve'
export const updateTableState =  'kt/updateTableState'
export const addOneNewOrder = 'kt/addOneNewOrder'
export const deleteOneOrder = 'kt/deleteOneOrder'
export const deleteOneOrderItemByOTnumber = 'kt/deleteOneOrderItemByOTnumber'
export const getOneOrderByOnumber = 'kt/getOneOrderByOnumber'
export const getAllStaff = 'kt/getAllStaff'
export const getReserveByNowTime = 'kt/getReserveByNowTime'
// export const deleteOneReserve = 'kt/deleteOneReserve'

